language: ruby
rvm:
  - 2.3.1
cache: bundler
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fe18055a45cdf1a5ecae
    on_success: change
    on_failure: always
    on_start: never
